-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema iskomartdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iskomartdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iskomartdb` DEFAULT CHARACTER SET utf8 ;
USE `iskomartdb` ;

-- -----------------------------------------------------
-- Table `iskomartdb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`USERS` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `FNAME` VARCHAR(255) NOT NULL,
  `LNAME` VARCHAR(255) NOT NULL,
  `DOB` DATE NOT NULL,
  `PHONE` VARCHAR(24) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `USERNAME` VARCHAR(255) NOT NULL,
  `GENDER` VARCHAR(8) NOT NULL,
  `STATUS` VARCHAR(255) NOT NULL,
  `PASSWORD_HASH` VARCHAR(255) NOT NULL,
  `AVATAR_URL` TINYTEXT NULL,
  `CREATED_ON` DATE NOT NULL,
  `ROLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`CUSTOMER` (
  `CUSTOMER_ID` INT NOT NULL,
  `DISPLAY_NAME` VARCHAR(255) NOT NULL,
  `BIO` TEXT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  CONSTRAINT `FK_customer_id`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `iskomartdb`.`USERS` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`NOTIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`NOTIFICATION` (
  `NOTIF_ID` INT NOT NULL AUTO_INCREMENT,
  `SUBJECT` VARCHAR(255) NOT NULL,
  `DESCRIPTION` MEDIUMTEXT NULL,
  `IMAGE_URL` TINYTEXT NULL,
  `REDIRECT_URL` TINYTEXT NULL,
  `TIMESTAMP` DATETIME(1) NOT NULL DEFAULT NOW(),
  `STATUS` VARCHAR(45) NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`NOTIF_ID`),
  INDEX `USER_ID_idx` (`USER_ID` ASC),
  CONSTRAINT `FK_NOTIF_USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `iskomartdb`.`USERS` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`MERCHANT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`MERCHANT` (
  `MERCHANT_ID` INT NOT NULL,
  `BU_EMAIL` VARCHAR(255) NOT NULL,
  `SHOP_NAME` VARCHAR(255) NOT NULL,
  `SHOP_DESC` TEXT NULL,
  `ADDRESS` VARCHAR(255) NOT NULL,
  `STUDENT_NUM` VARCHAR(45) NOT NULL,
  `ID_IMAGE_URL` TINYTEXT NULL,
  PRIMARY KEY (`MERCHANT_ID`),
  CONSTRAINT `FK_MERCHANT_ID`
    FOREIGN KEY (`MERCHANT_ID`)
    REFERENCES `iskomartdb`.`USERS` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`STAFF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`STAFF` (
  `STAFF_ID` INT NOT NULL AUTO_INCREMENT,
  `LAST_LOGIN` DATETIME(1) NULL,
  `STAFF_TYPE` VARCHAR(45) NOT NULL,
  `CREATION_DATE` DATETIME(1) NOT NULL DEFAULT NOW(),
  `STATUS` VARCHAR(45) NOT NULL,
  `CAN_CREATE` TINYINT NOT NULL,
  `LAST_ACTION` DATETIME(1) NULL,
  PRIMARY KEY (`STAFF_ID`),
  CONSTRAINT `STAFF_ID`
    FOREIGN KEY (`STAFF_ID`)
    REFERENCES `iskomartdb`.`USERS` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`MESSAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`MESSAGE` (
  `MSG_ID` INT NOT NULL AUTO_INCREMENT,
  `MSG_TEXT` TEXT NOT NULL,
  `SENT_ON` DATETIME(1) NOT NULL DEFAULT NOW(),
  `STATUS` VARCHAR(45) NOT NULL,
  `ATTACH_URL` VARCHAR(255) NULL,
  `ATTACH_FILETYPE` VARCHAR(45) NULL,
  `MESSAGEcol` VARCHAR(45) NULL,
  `MSG_RECEIVER` INT NULL,
  `MSG_SENDER` INT NULL,
  PRIMARY KEY (`MSG_ID`),
  INDEX `MSG_RECEIVER_idx` (`MSG_RECEIVER` ASC),
  INDEX `MSG_SENDER_idx` (`MSG_SENDER` ASC),
  CONSTRAINT `FK_MESSAGE_MSG_RECEIVER`
    FOREIGN KEY (`MSG_RECEIVER`)
    REFERENCES `iskomartdb`.`MERCHANT` (`MERCHANT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MESSAGE_MSG_SENDER`
    FOREIGN KEY (`MSG_SENDER`)
    REFERENCES `iskomartdb`.`CUSTOMER` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`ADDRESS_BOOK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`ADDRESS_BOOK` (
  `ADD_ID` INT NOT NULL,
  `RECEPIENT_NAME` VARCHAR(255) NOT NULL,
  `PHONE_NO` VARCHAR(45) NOT NULL,
  `REGION` VARCHAR(255) NOT NULL,
  `PROVINCE` VARCHAR(255) NOT NULL,
  `MUNCIT` VARCHAR(255) NOT NULL,
  `SPECIFIC` VARCHAR(255) NULL,
  `UNIT_FLOOR` VARCHAR(255) NULL,
  `POSTAL_CODE` VARCHAR(45) NULL,
  `ADDRESS_CAT` VARCHAR(255) NULL,
  `IS_DEFAULT` TINYINT NULL,
  `CUSTOMER_ID` INT NULL,
  PRIMARY KEY (`ADD_ID`),
  INDEX `CUSTOMER_ID_idx` (`CUSTOMER_ID` ASC),
  CONSTRAINT `FK_ADRESSBOOK_CUSTOMER_ID`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `iskomartdb`.`CUSTOMER` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`OFFERING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`OFFERING` (
  `OFFERING_ID` INT NOT NULL AUTO_INCREMENT,
  `OFFERING_NAME` VARCHAR(255) NOT NULL,
  `OFFERING_TYPE` CHAR(1) NOT NULL,
  `AVAIL_STATUS` VARCHAR(45) NOT NULL,
  `OFFERING_DESC` VARCHAR(255) NULL,
  `MERCHANT_ID` INT NOT NULL,
  PRIMARY KEY (`OFFERING_ID`),
  INDEX `MERCHANT_ID_idx` (`MERCHANT_ID` ASC),
  CONSTRAINT `FK_OFFERING_MERCHANT_ID`
    FOREIGN KEY (`MERCHANT_ID`)
    REFERENCES `iskomartdb`.`MERCHANT` (`MERCHANT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`SERVICE_CAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`SERVICE_CAT` (
  `SERCAT_ID` INT NOT NULL AUTO_INCREMENT,
  `CAT_NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`SERCAT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`SERVICE_SUBCAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`SERVICE_SUBCAT` (
  `SERSUBCAT_ID` INT NOT NULL AUTO_INCREMENT,
  `SUBCAT_NAME` VARCHAR(255) NOT NULL,
  `SERCAT_ID` INT NOT NULL,
  PRIMARY KEY (`SERSUBCAT_ID`),
  INDEX `SERCAT_ID_idx` (`SERCAT_ID` ASC),
  CONSTRAINT `FK_SUBCAT_SERCAT_ID`
    FOREIGN KEY (`SERCAT_ID`)
    REFERENCES `iskomartdb`.`SERVICE_CAT` (`SERCAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`SERVICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`SERVICE` (
  `SERVICE_ID` INT NOT NULL,
  `SER_DESC` VARCHAR(255) NOT NULL,
  `PRICE` INT NOT NULL,
  `DEPOSIT` INT NOT NULL DEFAULT 0,
  `SLOTS` INT NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `DELIVERY_METHOD` VARCHAR(255) NOT NULL,
  `POSTED_ON` DATETIME(1) NOT NULL,
  `MERCHANT_ID` INT NOT NULL,
  `SERSUBCAT_ID` INT NOT NULL,
  PRIMARY KEY (`SERVICE_ID`),
  INDEX `MERCHANT_ID_idx` (`MERCHANT_ID` ASC),
  INDEX `SERSUBCAT_ID_idx` (`SERSUBCAT_ID` ASC),
  CONSTRAINT `FK_SERVICE_ID`
    FOREIGN KEY (`SERVICE_ID`)
    REFERENCES `iskomartdb`.`OFFERING` (`OFFERING_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SERVICE_MERCHANT_ID`
    FOREIGN KEY (`MERCHANT_ID`)
    REFERENCES `iskomartdb`.`MERCHANT` (`MERCHANT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SERVICE_SERSUBCAT_ID`
    FOREIGN KEY (`SERSUBCAT_ID`)
    REFERENCES `iskomartdb`.`SERVICE_SUBCAT` (`SERSUBCAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`PROD_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`PROD_CATEGORY` (
  `PRODCAT_ID` INT NOT NULL AUTO_INCREMENT,
  `CAT_NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PRODCAT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`PROD_SUBCAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`PROD_SUBCAT` (
  `PRODSUBCAT_ID` INT NOT NULL AUTO_INCREMENT,
  `SUBCAT_NAME` VARCHAR(255) NOT NULL,
  `PRODCAT_ID` INT NOT NULL,
  PRIMARY KEY (`PRODSUBCAT_ID`),
  CONSTRAINT `FK_SUBCAT_PRODCAT_ID`
    FOREIGN KEY (`PRODCAT_ID`)
    REFERENCES `iskomartdb`.`PROD_CATEGORY` (`PRODCAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`PRODUCT` (
  `PROD_ID` INT NOT NULL,
  `PRICE` INT NOT NULL,
  `PROD_DESC` VARCHAR(255) NOT NULL,
  `STOCK_QTY` INT NOT NULL,
  `IS_PREORDER` TINYINT NOT NULL DEFAULT 0,
  `POSTED_ON` DATETIME(1) NOT NULL DEFAULT NOW(),
  `STATUS` VARCHAR(45) NOT NULL,
  `MERCHANT_ID` INT NOT NULL,
  `PRODSUBCAT_ID` INT NOT NULL,
  PRIMARY KEY (`PROD_ID`),
  INDEX `MERCHANT_ID_idx` (`MERCHANT_ID` ASC),
  INDEX `PRODSUBCAT_ID_idx` (`PRODSUBCAT_ID` ASC),
  CONSTRAINT `FK_PRODUCT_MERCHANT_ID`
    FOREIGN KEY (`MERCHANT_ID`)
    REFERENCES `iskomartdb`.`MERCHANT` (`MERCHANT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRODUCT_PRODSUBCAT_ID`
    FOREIGN KEY (`PRODSUBCAT_ID`)
    REFERENCES `iskomartdb`.`PROD_SUBCAT` (`PRODSUBCAT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRODUCT_PROD_ID`
    FOREIGN KEY (`PROD_ID`)
    REFERENCES `iskomartdb`.`OFFERING` (`OFFERING_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`SERVICE_REQUEST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`SERVICE_REQUEST` (
  `REQUEST_ID` INT NOT NULL AUTO_INCREMENT,
  `REQUEST_DATE` DATETIME(1) NOT NULL DEFAULT NOW(),
  `SCHEDULED_DATE` DATETIME(1) NOT NULL DEFAULT NOW(),
  `REQ_STATUS` VARCHAR(45) NOT NULL,
  `TOTAL_PRICE` INT NULL,
  `CUSTOMER_INFO` TEXT NOT NULL,
  `NOTE` VARCHAR(255) NULL,
  `RECEIPT_NAME` VARCHAR(255) NOT NULL,
  `ADDRESS` VARCHAR(255) NULL,
  `PHONE_NUM` VARCHAR(45) NULL,
  `CUSTOMER_ID` INT NOT NULL,
  `SERVICE_ID` INT NOT NULL,
  `RECIPIENT_NAME` VARCHAR(255) NULL,
  PRIMARY KEY (`REQUEST_ID`),
  INDEX `CUSTOMER_ID_idx` (`CUSTOMER_ID` ASC),
  INDEX `SERVICE_ID_idx` (`SERVICE_ID` ASC),
  CONSTRAINT `FK_REQUEST_CUSTOMER_ID`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `iskomartdb`.`CUSTOMER` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_REQUEST_SERVICE_ID`
    FOREIGN KEY (`SERVICE_ID`)
    REFERENCES `iskomartdb`.`SERVICE` (`SERVICE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`USER_LIKES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`USER_LIKES` (
  `LIKED_ID` INT NOT NULL AUTO_INCREMENT,
  `LIKED_ON` DATETIME(1) NOT NULL DEFAULT NOW(),
  `CUSTOMER_ID` INT NOT NULL,
  `OFFERING_ID` INT NOT NULL,
  PRIMARY KEY (`LIKED_ID`),
  INDEX `CUSTOMER_ID_idx` (`CUSTOMER_ID` ASC),
  INDEX `OFFERING_ID_idx` (`OFFERING_ID` ASC),
  CONSTRAINT `FK_USER_LIKES_CUSTOMER_ID`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `iskomartdb`.`CUSTOMER` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_LIKES_OFFERING_ID`
    FOREIGN KEY (`OFFERING_ID`)
    REFERENCES `iskomartdb`.`OFFERING` (`OFFERING_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`REVIEW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`REVIEW` (
  `REVIEW_ID` INT NOT NULL AUTO_INCREMENT,
  `RATING` INT NOT NULL,
  `DESCRIPTION` TEXT NULL,
  `REVIEWED_ON` DATETIME(1) NOT NULL DEFAULT NOW(),
  `CUSTOMER_ID` INT NOT NULL,
  `OFFERING_ID` INT NOT NULL,
  PRIMARY KEY (`REVIEW_ID`),
  INDEX `CUSTOMER_ID_idx` (`CUSTOMER_ID` ASC),
  INDEX `OFFERING_ID_idx` (`OFFERING_ID` ASC),
  CONSTRAINT `FK_REVIEW_CUSTOMER_ID`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `iskomartdb`.`CUSTOMER` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_REVIEW_OFFERING_ID`
    FOREIGN KEY (`OFFERING_ID`)
    REFERENCES `iskomartdb`.`OFFERING` (`OFFERING_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`REVIEW_ATTACH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`REVIEW_ATTACH` (
  `ATTACH_ID` INT NOT NULL AUTO_INCREMENT,
  `ATTACH_URL` TINYTEXT NOT NULL,
  `FILE_TYPE` VARCHAR(45) NOT NULL,
  `REVIEW_ID` INT NOT NULL,
  PRIMARY KEY (`ATTACH_ID`),
  INDEX `REVIEW_ID_idx` (`REVIEW_ID` ASC),
  CONSTRAINT `FK_ATTACHMENT_REVIEW_ID`
    FOREIGN KEY (`REVIEW_ID`)
    REFERENCES `iskomartdb`.`REVIEW` (`REVIEW_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`DISCOUNT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`DISCOUNT` (
  `DISCOUNT_ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(45) NOT NULL,
  `VALUE` INT NOT NULL,
  `START_DATE` DATETIME(1) NOT NULL DEFAULT NOW(),
  `END_DATE` DATETIME(1) NOT NULL DEFAULT NOW(),
  `OFFERING_ID` INT NOT NULL,
  PRIMARY KEY (`DISCOUNT_ID`),
  INDEX `OFFERING_ID_idx` (`OFFERING_ID` ASC),
  CONSTRAINT `FK_DISCOUNT_OFFERING_ID`
    FOREIGN KEY (`OFFERING_ID`)
    REFERENCES `iskomartdb`.`OFFERING` (`OFFERING_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`DELIVERY_METHOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`DELIVERY_METHOD` (
  `DM_ID` INT NOT NULL AUTO_INCREMENT,
  `DM_NAME` VARCHAR(64) NOT NULL,
  `DM_FEE` DOUBLE NULL,
  `DM_PROVIDER` VARCHAR(255) NULL,
  `NOTE` TINYTEXT NULL,
  `PROD_ID` INT NOT NULL,
  INDEX `FK_DM_PRODUCT_ID_idx` (`PROD_ID` ASC),
  PRIMARY KEY (`DM_ID`),
  CONSTRAINT `FK_DM_PRODUCT_ID`
    FOREIGN KEY (`PROD_ID`)
    REFERENCES `iskomartdb`.`PRODUCT` (`PROD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`ORDERS` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `ORDERED_ON` DATETIME(1) NOT NULL DEFAULT NOW(),
  `TOTAL_AMOUNT` INT NOT NULL,
  `ORDER_STATUS` VARCHAR(45) NOT NULL,
  `PAYMENT_STATUS` VARCHAR(45) NOT NULL,
  `RECEIVED_ON` DATETIME(1) NULL DEFAULT NOW(),
  `RECIPIENT_NAME` VARCHAR(255) NULL,
  `PHONE_NUM` VARCHAR(45) NULL,
  `ADDRESS` VARCHAR(255) NULL,
  `DISCOUNT_AMT` DOUBLE NULL,
  `DELIVERY_STATUS` VARCHAR(45) NOT NULL,
  `DISCOUNT_ID` INT NULL,
  `CUSTOMER_ID` INT NOT NULL,
  `DM_ID` INT NOT NULL,
  PRIMARY KEY (`ORDER_ID`),
  UNIQUE INDEX `ORDER_ID_UNIQUE` (`ORDER_ID` ASC),
  INDEX `FK_ORDER_DISCOUNT_ID_idx` (`DISCOUNT_ID` ASC),
  INDEX `FK_ORDER_CUSTOMER_ID_idx` (`CUSTOMER_ID` ASC),
  INDEX `FK_ORDER_DM_ID_idx` (`DM_ID` ASC),
  CONSTRAINT `FK_ORDER_DISCOUNT_ID`
    FOREIGN KEY (`DISCOUNT_ID`)
    REFERENCES `iskomartdb`.`DISCOUNT` (`DISCOUNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ORDER_CUSTOMER_ID`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `iskomartdb`.`CUSTOMER` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ORDER_DM_ID`
    FOREIGN KEY (`DM_ID`)
    REFERENCES `iskomartdb`.`DELIVERY_METHOD` (`DM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`ORDER_ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`ORDER_ITEM` (
  `ORDERITEM_ID` INT NOT NULL AUTO_INCREMENT,
  `PRICE` INT NOT NULL,
  `QUANTITY` INT NOT NULL,
  `ORDER_ID` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  PRIMARY KEY (`ORDERITEM_ID`),
  INDEX `PRODUCT_ID_idx` (`PRODUCT_ID` ASC),
  INDEX `ORDER_ID_idx` (`ORDER_ID` ASC),
  CONSTRAINT `FK_ITEM_ORDER_ID`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `iskomartdb`.`ORDERS` (`ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ITEM_PRODUCT_ID`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `iskomartdb`.`PRODUCT` (`PROD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`DISPLAY_IMG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`DISPLAY_IMG` (
  `DISPLAY_IMG_ID` INT NOT NULL AUTO_INCREMENT,
  `IMAGE_URL` TINYTEXT NOT NULL,
  `IS_DEFAULT` TINYINT NOT NULL DEFAULT 0,
  `OFFERING_ID` INT NOT NULL,
  PRIMARY KEY (`DISPLAY_IMG_ID`),
  INDEX `OFFERING_ID_idx` (`OFFERING_ID` ASC),
  CONSTRAINT `FK_DISPLAYIMG_OFFERING_ID`
    FOREIGN KEY (`OFFERING_ID`)
    REFERENCES `iskomartdb`.`OFFERING` (`OFFERING_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`PAYMENT_METHOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`PAYMENT_METHOD` (
  `PM_ID` INT NOT NULL AUTO_INCREMENT,
  `SERVICE` VARCHAR(255) NOT NULL,
  `LINK` VARCHAR(255) NULL,
  `QR_URL` TINYTEXT NULL,
  `NUMBER` VARCHAR(45) NULL,
  `USERNAME` VARCHAR(255) NULL,
  `OTHER` VARCHAR(255) NULL,
  `MERCHANT_ID` INT NOT NULL,
  PRIMARY KEY (`PM_ID`),
  INDEX `OFFERING_ID_idx` (`MERCHANT_ID` ASC),
  CONSTRAINT `FK_PAYMENTMETHOD_OFFERING_ID`
    FOREIGN KEY (`MERCHANT_ID`)
    REFERENCES `iskomartdb`.`MERCHANT` (`MERCHANT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`VOUCHER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`VOUCHER` (
  `VOUCHER_ID` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(255) NOT NULL,
  `DISCOUNT_TYPE` VARCHAR(255) NOT NULL,
  `DISCOUNT_VALUE` INT NOT NULL,
  `CAP` INT NULL,
  `MIN_SPEND` INT NOT NULL,
  `USAGE_LIMIT` INT NOT NULL,
  `EXPIRY_DATE` DATE NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `MERCHANT_ID` INT NOT NULL,
  PRIMARY KEY (`VOUCHER_ID`),
  INDEX `MERCHANT_ID_idx` (`MERCHANT_ID` ASC),
  CONSTRAINT `FK_VOUCHER_MERCHANT_ID`
    FOREIGN KEY (`MERCHANT_ID`)
    REFERENCES `iskomartdb`.`MERCHANT` (`MERCHANT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`VOUCHER_USAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`VOUCHER_USAGE` (
  `VU_ID` INT NOT NULL AUTO_INCREMENT,
  `USED_ON` VARCHAR(255) NOT NULL,
  `DISCOUNT_AMT` VARCHAR(45) NOT NULL,
  `VOUCHER_ID` INT NOT NULL,
  `REQUEST_ID` INT NULL,
  `ORDER_ID` INT NULL,
  PRIMARY KEY (`VU_ID`),
  INDEX `VOUCHER_ID_idx` (`VOUCHER_ID` ASC),
  INDEX `REQUEST_ID_idx` (`REQUEST_ID` ASC),
  INDEX `ORDER_ID_idx` (`ORDER_ID` ASC),
  CONSTRAINT `FK_VOUCHERUSAGE_VOUCHER_ID`
    FOREIGN KEY (`VOUCHER_ID`)
    REFERENCES `iskomartdb`.`VOUCHER` (`VOUCHER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VOUCHERUSAGE_REQUEST_ID`
    FOREIGN KEY (`REQUEST_ID`)
    REFERENCES `iskomartdb`.`SERVICE_REQUEST` (`REQUEST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VOUCHERUASGE_ORDER_ID`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `iskomartdb`.`ORDERS` (`ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`ALLOWED_PAYMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`ALLOWED_PAYMENT` (
  `ALLOWED_PM_ID` INT NOT NULL AUTO_INCREMENT,
  `STATUS` VARCHAR(45) NOT NULL,
  `PM_ID` INT NOT NULL,
  `OFFERING_ID` INT NOT NULL,
  PRIMARY KEY (`ALLOWED_PM_ID`),
  INDEX `OFFERING_ID_idx` (`OFFERING_ID` ASC),
  INDEX `FK_ALLOWEDPM_PM_ID_idx` (`PM_ID` ASC),
  CONSTRAINT `FK_ALLOWEDPM_PM_ID`
    FOREIGN KEY (`PM_ID`)
    REFERENCES `iskomartdb`.`PAYMENT_METHOD` (`PM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ALLOWEDPM_OFFERING_ID`
    FOREIGN KEY (`OFFERING_ID`)
    REFERENCES `iskomartdb`.`OFFERING` (`OFFERING_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iskomartdb`.`PAYMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iskomartdb`.`PAYMENT` (
  `PAYMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `REF_NUM` VARCHAR(255) NOT NULL,
  `AMOUNT` INT NOT NULL,
  `PAID_ON` DATETIME(1) NOT NULL DEFAULT NOW(),
  `ORDER_ID` INT NULL,
  `REQUEST_ID` INT NULL,
  `ALLOWED_PM_ID` INT NOT NULL,
  PRIMARY KEY (`PAYMENT_ID`),
  INDEX `ORDER_ID_idx` (`ORDER_ID` ASC),
  INDEX `REQUEST_ID_idx` (`REQUEST_ID` ASC),
  INDEX `ALLOWED_PM_ID_idx` (`ALLOWED_PM_ID` ASC),
  CONSTRAINT `FK_PAYMENT_ORDER_ID`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `iskomartdb`.`ORDERS` (`ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PAYMENT_REQUEST_ID`
    FOREIGN KEY (`REQUEST_ID`)
    REFERENCES `iskomartdb`.`SERVICE_REQUEST` (`REQUEST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PAYMENT_ALLOWED_PM_ID`
    FOREIGN KEY (`ALLOWED_PM_ID`)
    REFERENCES `iskomartdb`.`ALLOWED_PAYMENT` (`ALLOWED_PM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
