-- Add EMAIL_2FA table and EMAIL_2FA_ENABLED column to USERS

ALTER TABLE `USERS`
  ADD COLUMN `EMAIL_2FA_ENABLED` TINYINT(1) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS `EMAIL_2FA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `CODE_HASH` varchar(255) NOT NULL,
  `EXPIRES_AT` datetime NOT NULL,
  `ATTEMPTS` int(11) NOT NULL DEFAULT 0,
  `USED` tinyint(1) NOT NULL DEFAULT 0,
  `CREATED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  KEY `EMAIL_2FA_USER_IDX` (`USER_ID`),
  KEY `EMAIL_2FA_EXPIRES_IDX` (`EXPIRES_AT`),
  CONSTRAINT `FK_EMAIL_2FA_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
