CREATE TABLE IF NOT EXISTS `PASSWORD_RESETS` (
  `RESET_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `TOKEN_HASH` char(64) NOT NULL,
  `EXPIRES_AT` datetime NOT NULL,
  `USED_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`RESET_ID`),
  UNIQUE KEY `PASSWORD_RESETS_TOKEN_UNIQUE` (`TOKEN_HASH`),
  KEY `PASSWORD_RESETS_USER_IDX` (`USER_ID`),
  KEY `PASSWORD_RESETS_EXPIRES_IDX` (`EXPIRES_AT`),
  CONSTRAINT `FK_PASSWORD_RESETS_USER`
    FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`)
    ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
